회원가입 플로우 프론트
A-APT/DuckBox pull request #1
Opened 2022-01-10 06:47 UTC by Hongji0611

## 개요
- Font 추가, 회원가입 과정 프론트 제작 

## 상세내용
- 이메일 인증: 이메일의 유효성 확인과 약관 동의를 모두 했을 경우에만  인증하기 버튼이 활성화 됩니다.  

- 이메일 코드: 확인코드를 작성해야지만 제출버튼이 활성화됩니다. 지금은 예시로 적법한 코드를 '123456'으로 설정했고, 이와 동일하지 않은 코드를 작성할 경우 경고 메세지가 발생합니다. 인증코드 재전송을 누르면 해당 함수가 실행되도록 했으며, 현재는 모달창을 띄웁니다.  

- 학생증 인증 안내: 학생증 이미지 디자인을 수정했습니다. 인증하기 버튼을 누르면 카메라로 이동하게 될 예정입니다.  
- 학생증 정보 입력: 이미지에는 실제 이미지가 삽입될 예정입니다. 이미지에서 추출한 정보를 수정할 수 있습니다. 정보의 유효성 기준을 적용할 수 있습니다. 재촬영하기 버튼을 누르면 카메라로 이동하게 될 예정입니다.  
- 추가정보 입력: 각 정보를 모두 입력해야지만 완료버튼이 활성화됩니다. 비밀번호(8자이상, 문자 숫자 특수문자 1자 이상), 비밀번호확인(동일한 비밀번호 입력), 닉네임(중복여부), 학과(학과리스트)의 유효성을 확인합니다. 추후 서버와 연동하게된다면 유효성 확인 코드가 다른 파일로 이동될 수 있습니다.  

## 리뷰어가 확인할 사항
- stack등 패키지들을 설치했으므로 `npm install` 한번 해주고 실행하기 바랍니다!

## 기타
- 학생증 정보(이름, 학번)의 유효성 체크의 기준을 논의해야합니다.
- 회원가입 완료 후 홈으로 이동할지, 다시 로그인을 시킬지 논의해야 합니다.
- 이용약관, 개인정보처리방침 내용을 정리해야 합니다.

2022-01-11 12:01 UTC, 0JIEUN0 requested changes
작업 대박이네요 너무 수고하셨습니다!!!

2022-01-11 12:01 UTC, 0JIEUN0 commented on src/containers/user/did/MoreInfoScreen.js
> +    const checkDepartMentList = () => {
중요한건 아닌데 M 대문자 이유가 있을까요? (checkDepart'M'entList)

2022-01-11 12:01 UTC, 0JIEUN0 commented on src/containers/common/PasswordBox.js
> +function PasswordBox({ playsholder, text, setText, isCorrect, setCorrect, correctText }) {
이게 `correctText` 가 "알맞은 문자" 라는 느낌이 드는데 실제로는 invalid 입력에 대한 오류 안내 문자더라구요.
변수 이름을 warningText, errorText ? 이런 느낌으로 바꾸는건 어떤가요?

2022-01-11 12:01 UTC, 0JIEUN0 commented on src/containers/user/did/EmailCodeScreen.js
> +                    <SubButton text="인증코드 재전송" doFunction={ doFunction }/>
이 부분이 디자인 화면엔 없는 것 맞나요?
가 아니라 디자인 화면에는 "인증코드 다시 보내기" 라고 되어있네요
다른 text 도 다른 부분이 있는 것 같은데 지금 단계에 부탁드려도 되는진 모르겠지만, 가능하다면 통일하면 좋을 것 같아요..! 이건 어떻게 작업하실지 알려주세요! (일단은 이렇게 or 통일

2022-01-11 12:01 UTC, 0JIEUN0 commented on src/containers/user/did/EmailCodeScreen.js
> +                    <SubButton text="인증코드 재전송" doFunction={ doFunction }/>
그리고 `SubButton` 이 어떤 것이길래 sub 이 붙었는지 본건데, 
사실상 SubButton 보다는 TextButton 이라고 보여요, 다소 사소하지만 요 네이밍도 한번 검토해주세요!

2022-01-12 13:51 UTC, Hongji0611 commented on src/containers/user/did/MoreInfoScreen.js
> +    const checkDepartMentList = () => {
습관적으로.. 그랬네요 수정했습니다!! 감사합니다

2022-01-12 13:53 UTC, Hongji0611 commented on src/containers/user/did/EmailCodeScreen.js
> +                    <SubButton text="인증코드 재전송" doFunction={ doFunction }/>
correctText와 SubButton 네이밍 변경했습니다! 역시 네이밍이 제일 어려워요..
피그마에 기존 디자인 아래쪽에 확정된 디자인을 두었습니다! 회의때 다시한번 말씀드릴게요 의견주셔서 감사합니다😄

2022-01-12 14:31 UTC, 0JIEUN0 commented on src/containers/user/did/EmailCodeScreen.js
> +                    <SubButton text="인증코드 재전송" doFunction={ doFunction }/>
아아하 네 알겠습니다!! 짱짱

2022-01-13 07:46 UTC, mimwin reviewed
정말 멋있어요 ㅠㅠ 코드 보고 열심히 공부해요 정말 고생많았어요!!

2022-01-13 07:46 UTC, mimwin commented on src/containers/user/did/CheckEmailScreen.js
> +                <InputBox playsholder={"학교 이메일을 입력해주세요"} text={email} setText={setEmail} isCorrect={isCorrect} setCorrect={setCorrect} correctText={"올바르지 않은 이메일 형식입니다."}/>
모바일 기기로 실행했을 때 "올바르지 않은 이메일 형식입니다." 이 글자만큼 공간은 생기는데 글자가 안 보이네요.

2022-01-13 07:46 UTC, mimwin commented on src/containers/user/did/EmailCodeScreen.js
> +                <InputBox playsholder={"인증코드를 입력해주세요"} text={code} setText={setCode} isCorrect={isCorrect} setCorrect={setCorrect} warningText={"올바르지 않은 코드입니다."}/>
"올바르지 않은 코드입니다"가 출력될 때 
피그마에선 '인증번호 입력박스'와 '인증번호를 받지 못하셨나요' 의 간격이 동일한데 
실제 실행화면에선 "올바르지 않은 코드입니다" 공간만큼 간격이 늘어나네요.  
사소한 간격이지만.. 혹시나 해서 물어봅니다!

2022-01-13 07:55 UTC, mimwin reviewed
마지막 화면에서 놓친게 있어서 추가 수정합니다..!

2022-01-13 07:55 UTC, mimwin commented on src/containers/user/did/MoreInfoScreen.js
> +                <InputBox playsholder={"입력해주세요."} text={department} setText={setDepartment} isCorrect={isCorrectDepartment} setCorrect={setCorrectDepartment} warningText={"정확한 학과명을 입력해야합니다."} />
학과명에 "hh" 쓰고 완료하기 눌러서 완료화면으로 간 다음 뒤로 가기를 눌렀더니
학과명 이름 박스 아래 경고문이 떠있네요
아직 학과리스트가 없어서 확실한 건 없지만 완료화면에서 뒤로가기를 없애도 될 거 같아요!

2022-01-14 04:05 UTC, Hongji0611 commented on src/containers/user/did/EmailCodeScreen.js
> +                    <SubButton text="인증코드 재전송" doFunction={ doFunction }/>
저번 회의 결과, 다시 SubButton으로 변경했습니다!

2022-01-14 04:05 UTC, Hongji0611 commented on src/containers/user/did/CheckEmailScreen.js
> +                <InputBox playsholder={"학교 이메일을 입력해주세요"} text={email} setText={setEmail} isCorrect={isCorrect} setCorrect={setCorrect} correctText={"올바르지 않은 이메일 형식입니다."}/>
correctText를 warningText로 변경하면서 여기에 적용을 하지 못했었네요!! 꼼꼼한 분석 감사합니다!

2022-01-14 04:06 UTC, Hongji0611 commented on src/containers/user/did/EmailCodeScreen.js
> +                <InputBox playsholder={"인증코드를 입력해주세요"} text={code} setText={setCode} isCorrect={isCorrect} setCorrect={setCorrect} warningText={"올바르지 않은 코드입니다."}/>
경고 문구 공간을 유지한 채로 문구만 뜨도록 변경했습니다! (간격 늘어남 없어짐)

2022-01-14 04:07 UTC, Hongji0611 commented on src/containers/user/did/MoreInfoScreen.js
> +                <InputBox playsholder={"입력해주세요."} text={department} setText={setDepartment} isCorrect={isCorrectDepartment} setCorrect={setCorrectDepartment} warningText={"정확한 학과명을 입력해야합니다."} />
닉네임과 학과명 로직을 조금 수정했습니다. useState를 사용할 경우 화면 전환보다 약간 늦게 업데이트 되더라고요.. 그래서 flag를 사용했지만 혹시 더 좋은 의견 있으시면 공유 부탁드립니다!!
완료 화면에서 뒤로가기도 없앴습니다😄

2022-01-14 04:23 UTC, 0JIEUN0 commented on src/containers/user/did/CheckEmailScreen.js
> +                <InputBox playsholder={"학교 이메일을 입력해주세요"} text={email} setText={setEmail} isCorrect={isCorrect} setCorrect={setCorrect} correctText={"올바르지 않은 이메일 형식입니다."}/>
아 오오 이런 이유였군요

2022-01-14 04:35 UTC, 0JIEUN0 commented on src/containers/user/did/MoreInfoScreen.js
> +                <InputBox playsholder={"입력해주세요."} text={department} setText={setDepartment} isCorrect={isCorrectDepartment} setCorrect={setCorrectDepartment} warningText={"정확한 학과명을 입력해야합니다."} />
`checkDuplication` 에 있던 `setCorrectNickname` 이 `onCheckAvailablity` 로 옮겨갔다, 라고 이해해서
이렇게 옮김으로 얻는 이점이 뭔지 설명해주실 수 있나요?

원래 코드의, map 으로 모든 요소에 대해 setState 해주는 것을 지금의 형태로 바꾸신 것은 정말 좋습니다!
그런데 바꾸신 이유가 state 가 늦게 업데이트 (useState 가 비동기 함수라 그렇습니다) 되는 것이라면, 함수 실행 후에 set 하는 부분이 있으니, 어떤 점에서 달라진 것인지 궁금해져서 여쭙니다.

2022-01-14 04:40 UTC, Hongji0611 commented on src/containers/user/did/MoreInfoScreen.js
> +                <InputBox playsholder={"입력해주세요."} text={department} setText={setDepartment} isCorrect={isCorrectDepartment} setCorrect={setCorrectDepartment} warningText={"정확한 학과명을 입력해야합니다."} />
이전 코드는 map에서 매번 useState를 set하는 과정을 거쳤다면, 지금은 함수 실행 이후 한번만 set을 하기 때문에 좀더 과부하가 적을 것이라고..? 예상합니다 (단순히 저의 생각입니다)

2022-01-14 04:42 UTC, 0JIEUN0 commented on src/containers/user/did/MoreInfoScreen.js
> +                <InputBox playsholder={"입력해주세요."} text={department} setText={setDepartment} isCorrect={isCorrectDepartment} setCorrect={setCorrectDepartment} warningText={"정확한 학과명을 입력해야합니다."} />
말씀하신 사항 저도 동의합니다!!
그럼 아무래도 기존보다는 원하시는 방향으로 동작할 것 같네요 ㅎㅎ

2022-01-14 04:43 UTC, 0JIEUN0 approved these changes
수고하셨습니다! 👍👍

(첫 PR 기념 ✨🎉🎉🎊🥳🎈)

2022-01-14 04:43 UTC, merged